### ISSUE TITLE
pythreejs renderer object does not show in jupyter lab

### ISSUE THREAD

**Issue by ivoihrke** [cihologramas/pyoptools#84] opened 2020-09-25 18:21 UTC
Hi, 

I am in the early steps of trying your project and I am having trouble replicating Tutorial 0; in particular, 
I do not get the interactive renderer to work. I installed the pythreekjs extension and jupyter lab shows
the extension manager as well as the pythreejs extension to be enabled. I can run the commands that you
provide in tutorial 0, however, the output for the Plot3D(S) command is simply a string describing the renderer 
object. 

Renderer(camera=OrthographicCamera(bottom=-100.0, children=(DirectionalLight(intensity=0.7, position=(0.0, 100…

Changing to 

renderer=Plot3D(S)
display(renderer)

which seems to be the way that the renderer is supposed to be used (according the the pythreejs documentation)
again yields the same string. 

Has anyone run into this issue before ? I am sort of stuck and there is no other visualization as far as I have explored. If you can point me to an alternative way of visualizing, that would also be helpful.

A question on the side: is there a visualization using an ipython console on the shell, or even just one that would pop up a matplotlib window when a python script is run with the interpreter "python pyoptools_test.py" ?

Any input is appreciated and thanks for putting this project up. 

best regards

**Comment by ivoihrke** [comment] 2020-09-25 18:34
This seems to be a pythreejs issue. I am following this: 

https://github.com/jupyter-widgets/pythreejs/issues/334

This, again may have to do with: 

https://github.com/jupyter-widgets/ipywidgets/issues/2220

**Comment by ivoihrke** [comment] 2020-09-25 18:42
This seems to be a pythreejs issue. I am following this: 

https://github.com/jupyter-widgets/pythreejs/issues/334

This, again may have to do with: 

https://github.com/jupyter-widgets/ipywidgets/issues/2220

I installed 

jupyter labextension install @jupyter-widgets/jupyterlab-manager

and am now getting the message: "Error displaying widget: model not found", which leads to:

https://stackoverflow.com/questions/57028962/jupyter-matplotlib-error-displaying-widget-model-not-found

**Comment by ivoihrke** [comment] 2020-09-25 18:46
I am running 

JupyterLab v1.2.6
Known labextensions:
   app dir: /mnt/ubuntu/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyter-threejs v2.2.0  enabled  OK
        jupyterlab-datawidgets v6.3.0  enabled  OK

**Comment by ivoihrke** [comment] 2020-09-25 19:00
Trying to check ipywidgets with a simple test; they don't work, they're getting stuck at this problem:

https://github.com/jupyter-widgets/ipywidgets/issues/2623

**Comment by ivoihrke** [comment] 2020-09-25 19:03
ipywidgets is actually working; I ran into the same problem as the person in the thread; i tried on the console, not in a notebook

**Comment by ivoihrke** [comment] 2020-09-25 19:12
I am giving up on this right now - I would appreciate an answer on alternative plotting if there is any. Thank you...

**Comment by ramezquitao** [comment] 2020-10-11 15:04
I apologize for the delay answering. There was another version implemented some time ago, that didn't allow to interact with the plot. But the setup eas quite compicated as it required some special version of the MESA libraries installed to allow offscreen rendering. At the moment all I can suggest is to use a standard Jupyter notebook instead of  jupyther lab. Would this work for you?

**Comment by ramezquitao** [comment] 2023-01-05 15:05
Today I tested and the problem is now the opposite. Everything is working in Jupyterlabs, but the render object is not visible in the old Jupyter notebook. As everyone should be moving to Jupyterlabs, this issue will be closed.

**Closed by ramezquitao** 2023-01-05 15:05 UTC
